# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_inv_involvement <- function(arr) {
    .Call(`_rmed_get_inv_involvement`, arr)
}

get_inv_count <- function(arr) {
    .Call(`_rmed_get_inv_count`, arr)
}

get_inv_pairs <- function(v, lines) {
    .Call(`_rmed_get_inv_pairs`, v, lines)
}

median_slopes <- function(x, y, idx, mdn_idx) {
    .Call(`_rmed_median_slopes`, x, y, idx, mdn_idx)
}

median_estimator <- function(x, y) {
    .Call(`_rmed_median_estimator`, x, y)
}

