# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_inv_pairs <- function(v, lines) {
    .Call(`_rmed_get_inv_pairs`, v, lines)
}

get_conc_count <- function(arr) {
    .Call(`_rmed_get_conc_count`, arr)
}

